template_path: templates/versioned-ecs-cluster.yaml

parameters:
  AssetInsightId: "{{ var.AssetInsightId }}"
  Version:
  MicroserviceName: {{ var.MicroserviceName }}
  Env: {{ var.ProdEnvShortName }}

stack_tags:
  "tr:financial-identifier": "{{ var.FinancialIdentifier }}"
  "tr:application-asset-insight-id": "{{ var.AssetInsightId }}"
  "tr:environment-type": {{ var.ProdEnvFullName }}
  "tr:resource-owner": {{ var.ResourceOwner }}
  "tr:service-name": {{ var.MicroserviceName }}
